services:
  back:
    image: tiagosilva000/lab-docker-back:latest
    environment:
      - CURRENT_ENVIRONMENT=dev
    ports:
      - "8081:5000"

  front:
    image: tiagosilva000/lab-docker-front:latest
    environment:
      - WS_BACK_URL=http://back:5000
    ports:
      - "8082:80"
